language: php
php:
  - 5.5
  - 5.4


before_script:
  - composer install


script:
  - vendor/bin/phpunit test/ 

notifications:
  webhooks:
    - https://idobata.io/hook/travis_ci/22e5a58c-e633-4c04-a5c4-42083c471739
